export const locations = [
    {
        title: 'Sydney',
        meta: {},
        items: [
            { title: 'Newtown', slug: 'newtown' },
            { title: 'Redfern', slug: 'redfern' },
            { title: 'Surry Hills', slug: 'surry-hills' },
            { title: 'Ultimo', slug: 'ultimo' },
            { title: 'Alexandria', slug: 'alexandria' },
            { title: 'Waterloo', slug: 'waterloo' },
            { title: 'Petersham', slug: 'petersham' },
            { title: 'Summer Hill', slug: 'summer-hill' },
            { title: 'Dulwich Hill', slug: 'dulwich-hill' },
            { title: 'Leichhardt', slug: 'leichhardt' },
            { title: 'Annandale', slug: 'annandale' },
            { title: 'Glebe', slug: 'glebe' },
            { title: 'Eveleigh', slug: 'eveleigh' },
            { title: 'Rosebery', slug: 'rosebery' },
            { title: 'Ashfield', slug: 'ashfield' },
            { title: 'Zetland', slug: 'zetland' },
            { title: 'Mascot', slug: 'mascot' },
            { title: 'Kensington', slug: 'kensington' },
            { title: 'Darlinghurst', slug: 'darlinghurst' },
            { title: 'Marrickville', slug: 'marrickville' },
            { title: 'Potts Point', slug: 'potts-point' },
            { title: 'Coogee', slug: 'coogee' },
            { title: 'Bondi', slug: 'bondi' },
            { title: 'Mosman', slug: 'mosman' },
            { title: 'Parramatta', slug: 'parramatta' },
            { title: 'Ryde', slug: 'ryde' },
            { title: 'Balmain', slug: 'balmain' },
            { title: 'Hornsby', slug: 'hornsby' },
            { title: 'North Sydeny', slug: 'north-sydney' },
            { title: 'Bronte', slug: 'bronte' },
            { title: 'Burwood', slug: 'burwood' },
            { title: 'Strathfield', slug: 'strathfield' },
        ],
    },
    {
        title: 'Melbourne',
        meta: {},
        items: [
            { title: 'St Kilda', slug: 'st-kilda' },
            { title: 'Brighton', slug: 'brighton' },
            { title: 'Southbank', slug: 'southbank' },
            { title: 'Abbotsford', slug: 'abbotsford' },
            { title: 'Brunswick', slug: 'brunswick' },
            { title: 'Carlton', slug: 'carlton' },
            { title: 'Coburg', slug: 'coburg' },
            { title: 'Collingwood', slug: 'collingwood' },
            { title: 'Craigieburn', slug: 'craigieburn' },
            { title: 'Footscary', slug: 'footscary' },
            { title: 'Docklands', slug: 'docklands' },
            { title: 'Elwood', slug: 'elwood' },
            { title: 'Essendon', slug: 'essendon' },
            { title: 'Hawthorn', slug: 'hawthorn' },
            { title: 'Kew', slug: 'kew' },
            { title: 'Pakenham', slug: 'pakenham' },
            { title: 'Prahran', slug: 'parahran' },
            { title: 'Reservoir', slug: 'reservoir' },
            { title: 'South Melbourne', slug: 'south-melbourne' },
            { title: 'Thornbury', slug: 'thornbury' },
        ],
    },
];

export const cities = ['Sydney', 'Melbourne'];
